name: kookle web CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  S3_BUCKET_NAME: kookle-deploy
  AWS_REGION: ap-northeast-2
  CODE_DEPLOY_APPLICATION_NAME: kookle
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: kookle-front

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          node-version: '18'

      - name: Check Node v
        run: node -v
        
      - name: Generate Environment Variables File for Production
        run: 
          echo "VITE_API_URL=$VITE_API_URL" >> .env
        env: 
          VITE_API_URL: ${{ secrets.VITE_API_URL }}

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          CI: ""

      - name: Make zip file
        run: zip -qq -r ./kookle-front.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp --region ap-northeast-2 \
          ./kookle-front.zip s3://$S3_BUCKET_NAME/kookle-front.zip

      - name: Deploy to AWS EC2 from S3
        run: |
          aws deploy create-deployment \
          --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=$S3_BUCKET_NAME,key=kookle-front.zip,bundleType=zip
